### ISSUE TITLE
Error al intentar parsear author de Git sin nombre

### ISSUE THREAD

**Issue by npasserini** [faloi/yanapiri#41]
Al intentar crear la entrega para este repositorio https://github.com/obj1unq/2019s1-e4-semillas-ZekielAsh/commits/master produce un error: 

```
Traceback (most recent call last):
	20: from /usr/local/bin/yanapiri:23:in `<main>'
	19: from /usr/local/bin/yanapiri:23:in `load'
	18: from /var/lib/gems/2.5.0/gems/yanapiri-0.4.4/bin/yanapiri:5:in `<top (required)>'
	17: from /var/lib/gems/2.5.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	16: from /var/lib/gems/2.5.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	15: from /var/lib/gems/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	14: from /var/lib/gems/2.5.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	13: from /var/lib/gems/2.5.0/gems/yanapiri-0.4.4/lib/yanapiri/cli.rb:90:in `corregir'
	12: from /var/lib/gems/2.5.0/gems/yanapiri-0.4.4/lib/yanapiri/cli.rb:142:in `foreach_entrega'
	11: from /var/lib/gems/2.5.0/gems/yanapiri-0.4.4/lib/yanapiri/cli.rb:129:in `foreach_repo'
	10: from /var/lib/gems/2.5.0/gems/yanapiri-0.4.4/lib/yanapiri/cli.rb:129:in `chdir'
	 9: from /var/lib/gems/2.5.0/gems/yanapiri-0.4.4/lib/yanapiri/cli.rb:133:in `block in foreach_repo'
	 8: from /var/lib/gems/2.5.0/gems/yanapiri-0.4.4/lib/yanapiri/cli.rb:133:in `each'
	 7: from /var/lib/gems/2.5.0/gems/yanapiri-0.4.4/lib/yanapiri/cli.rb:134:in `block (2 levels) in foreach_repo'
	 6: from /var/lib/gems/2.5.0/gems/yanapiri-0.4.4/lib/yanapiri/cli.rb:134:in `chdir'
	 5: from /var/lib/gems/2.5.0/gems/yanapiri-0.4.4/lib/yanapiri/cli.rb:135:in `block (3 levels) in foreach_repo'
	 4: from /var/lib/gems/2.5.0/gems/yanapiri-0.4.4/lib/yanapiri/cli.rb:144:in `block in foreach_entrega'
	 3: from /var/lib/gems/2.5.0/gems/yanapiri-0.4.4/lib/yanapiri/entrega.rb:50:in `to_s'
	 2: from /var/lib/gems/2.5.0/gems/yanapiri-0.4.4/lib/yanapiri/entrega.rb:57:in `formato_humano'
	 1: from /var/lib/gems/2.5.0/gems/i18n-0.9.5/lib/i18n.rb:258:in `localize'
/var/lib/gems/2.5.0/gems/i18n-0.9.5/lib/i18n/backend/base.rb:75:in `localize': Object must be a Date, DateTime or Time object. nil given. (I18n::ArgumentError)
```

El problema está en esta línea en `entrega.rb`
```
      string << if hay_cambios? then "modificada por última vez #{formato_humano fecha}" else "sin cambios" end
```
o más bien en el método fecha que devuelve nil (o algo así), acá: `@repo.log.first.author_date`

Me quedé ahí no supe cómo seguir.

**Comment by faloi** [comment]
¿Y qué comando fue el que tiraste?

**Comment by npasserini** [comment]
`yanapiri corregir 2019s1-e4-semillas --commit-base
729e78ed1fbfaa7a0b933c930031f274ffdd3fce --fecha-limite "2019-06-11 22:15"`

**Comment by faloi** [comment]
Mmmm, es como si el commit no tuviera fecha, que es lo que calcula esa línea. Decime qué orga estás usando y lo pruebo.

(Asumo que antes de `corregir` ejecutaste `clonar`.)

**Comment by npasserini** [comment]
Sí.

**Comment by faloi** [comment]
Che pero recién me fijé y el pull request está creado. ¿Cómo hiciste al final?

**Comment by faloi** [comment]
Ya descubrí por dónde viene, es un error muy extraño.

Si tirás un `git log` vas a ver que el commit tiene mail pero no tiene nombre: `Author:  <sherlock-ezequiel@hotmail.com>` y eso hace que la biblioteca de Git que uso en Ruby no parsee nada, y por lo tanto la fecha queda `nil`.

Lo extraño es que no estoy pudiendo aislarlo, porque `git` no me deja commitear si no pongo un author name. Habría que hablar con el/la estudiante y que nos cuente cómo llegó a hacer un commit así (si es que se acuerda, claro).

**Comment by npasserini** [comment]
Los estudiantes de git usan el plugin de sgit que hizo Lucas, tal vez
usando una lib eso saltea alguna validación que deberíamos hacer.

¿Cómo hice? En realidad el error no está al armar el PR en sí, sino en la
línea que pasé más arriba, es sólo el imprimir la fecha en consola que
falla, así que le di una solución "temporal" ¯\_ツ_/¯

**Comment by faloi** [comment]
Es raro, porque git no te deja commitear sin nombre. Por el log pareciera
que el nombre es " ", pero desde Ruby no pude generar un commit así
(alguien hace un trim en alguna parte).

¿Tal vez Lucas tenga alguna pista de cómo pudo haber pasado?

**Comment by faloi** [comment]
@51lv3str1 ¿alguna idea?
